name: robotkernel

channels:
  - conda-forge
  - nodefaults

dependencies:
  - faker
  - geckodriver
  - ipywidgets
  - jupyter-starters
  - jupyterlab <4
  - jupyterlab_robotmode
  - matplotlib-base
  - nodejs >=18,<19
  - opencv
  - pillow
  - pip
  - python
  - requests
  - restinstance
  - rise
  - robotframework
  - robotframework-seleniumlibrary
  - robotframework-seleniumscreenshots
  - selenium
  - urllib3
  - wrapt
  - pip:
    - robotframework-faker
