name: "smoketest"
on:
  push:
  pull_request:
jobs:
  smoketest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        robotframework-version: [rf31, rf32, rf40]
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: robots-from-jupyter
    - run: nix-shell setup.nix -A shell --argstr robotframework ${{ matrix.robotframework-version }} --run "make test && python -m robotkernel.install && jupyter nbconvert --execute tests/Smoketest.ipynb && nbrobot -v BROWSER:headlessfirefox -F ipynb tests atest"
